SSH_KEY_PATH = "/Users/liamdupeyron/Desktop/AnswersAi/answerai.pem"
SSH_HOST = "3.136.57.217"
SSH_USER = "ubuntu"

MYSQL_HOST = "answer-ai-read.ceyenxdmnayo.us-east-2.rds.amazonaws.com"
MYSQL_USER = "admin"
MYSQL_PASSWORD = "XxK33vR7LlYKOVYGOZoC"
MYSQL_DB = "answer-ai"
MYSQL_PORT = "3306"

